# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20190925_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonc',
            name='dumb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buttonc',
            name='fat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buttonc',
            name='stupid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
