# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20190925_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttoncount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('dumb', models.PositiveIntegerField(default=0)),
                ('stupid', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Buttonc',
        ),
    ]
